### ISSUE TITLE
大佬，这种情况怎么办呀

### ISSUE THREAD

**Issue by Ran-Xing** [XHMM/chrome-extension-cookies#1]
<img width="717" alt="image" src="https://user-images.githubusercontent.com/73819467/168420029-2c7a9bf1-1769-4274-b88b-d6a3e1241e3f.png">

**Comment by XHMM** [comment]
hi，请问截图要表达什么意思呢？不太理解

**Comment by Ran-Xing** [comment]
就是cookies是通过第三方api获取到的

**Comment by XHMM** [comment]
你可以通过更改 [domain](https://github.com/XHMM/chrome-extension-cookies/blob/0008e164466cbbcc992a8f1904a1bfb8c86c386a/src/popup.ts#L16) 来读取对应域名下的 cookies，如果想要同时获取多个域名的话，就写个 for 循环之类的调用 getAll 即可，当然如果不想写死在代码里，可以在 popup 里加个个输入框UI来进行配置
